export default {
  messages: {
    en: {
      route: {
        overview: 'Overview',
        malwares: 'Malwares',
        engines: 'Engines',
        users: 'Users',
        groups: 'Groups',
        Settings: 'Settings'
      },
      actions: 'Action',
      details: 'Details',
      edit: 'Edit',
      delete: 'Delete',
      cancel: 'Cancel',
      save: 'Save',
      description: 'Description',
      add: 'Add',
      update: 'Update',
      read: 'Read',
      customize: 'Customize',
      messageDelete: "Do you really want to delete this record? This action can'nt be undone!",
      malwares: 'Malwares',
      editMalware: 'Edit Malware',
      newMalware: 'New Malware',
      engines: 'Engines',
      editEngine: 'Edit Engine',
      newEngine: 'New Engine',
      groups: 'Groups',
      editGroup: 'Edit Group',
      newGroup: 'New Group',
      source: 'Source',
      md5: 'MD5',
      sha1: 'SHA1',
      sha256: 'SHA256',
      copyToClipboard: 'Copied to clipboard',
      type: 'Type',
      enabled: 'Enabled',
      disabled: 'Disabled',
      status: 'Status',
      name: 'Name',
      key: 'Key',
      url: 'URL',
      permissions: 'Permissions',
      group: 'Group',
      users: 'Users',
      newUser: 'New User',
      editUser: 'Edit User',
      malwareToday: 'Malware New',
      totalMalware: 'Total Malware',
      engineEnabled: 'Engine Enabled',
      totalEngine: 'Total Engine',
      recentThreatEvents: 'Recent Malwares in My Database',
      detectedThreats: 'Detected Threats',
      sourcesInMyDB: 'Sources in My Database',
      oldPassword: 'Old Password',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      subtitle: {
        engine: 'Engine management',
        malware: 'Malware management',
        group: 'Group management',
        user: 'User management'
      }
    },
    vi: {
      route: {
        overview: 'Tổng Quan',
        malwares: 'Mã độc',
        engines: 'Phương pháp',
        users: 'Người dùng',
        groups: 'Nhóm người dùng',
        Settings: 'Cài đặt'
      },
      actions: 'Hành động',
      details: 'Chi Tiết',
      edit: 'Chỉnh sửa',
      delete: 'Xóa',
      cancel: 'Hủy',
      save: 'Lưu',
      description: 'Mô Tả',
      add: 'Thêm mới',
      update: 'Chỉnh sửa',
      read: 'Đọc',
      oldPassword: 'Mật Khẩu Cũ',
      password: 'Mật Khẩu',
      confirmPassword: 'Xác Nhận Mật Khẩu',
      customize: 'Tùy Chỉnh',
      messageDelete: 'Bạn có chắc chắn muốn xóa bản ghi này không? Hành động này không thể quay lại!',
      malwares: 'Mã độc',
      editMalware: 'Chỉnh sửa mã độc',
      newMalware: 'Thêm mã độc',
      engines: 'Phương pháp',
      editEngine: 'Chỉnh sửa phương pháp',
      newEngine: 'Thêm phương pháp',
      source: 'Nguồn',
      md5: 'MD5',
      sha1: 'SHA1',
      sha256: 'SHA256',
      copyToClipboard: 'Sao chép vào khay nhớ tạm',
      type: 'Loại',
      enabled: 'Đã Bật',
      disabled: 'Đã Tắt',
      status: 'Trạng Thái',
      name: 'Tên',
      key: 'Mã xác thực',
      url: 'URL',
      groups: 'Nhóm người dùng',
      editGroup: 'Chỉnh sửa nhóm người dùng',
      newGroup: 'Thêm nhóm người dùng',
      users: 'Người dùng',
      newUser: 'Thêm người dùng',
      editUser: 'Chỉnh sửa người dùng',
      permissions: 'Quyền',
      group: 'Nhóm',
      username: 'Tên đăng nhập',
      malwareToday: 'Mã độc mới',
      totalMalware: 'Tổng mã độc',
      engineEnabled: 'Engine đã bật',
      totalEngine: 'Tổng Engine',
      recentThreatEvents: 'Mã độc Gần Đây',
      detectedThreats: 'Mã độ Được Phát Hiện',
      sourcesInMyDB: 'Ngồn data trong cơ sở dữ liệu',
      subtitle: {
        engine: 'Quản lý phương pháp',
        malware: 'Quản lý mã độc ',
        group: 'Quản lý nhóm người dùng',
        user: 'Quản lý người dùng'
      }
    }
  }
}
